// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package greeter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// SayHello will register a user in the database, and return a nice message
	// to the caller.
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
	// GayGoodbye will remove the user from the database, and return a nice
	// message to the caller.
	SayGoodbye(ctx context.Context, in *SayGoodbyeRequest, opts ...grpc.CallOption) (*SayGoodbyeResponse, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

var greeterSayHelloStreamDesc = &grpc.StreamDesc{
	StreamName: "SayHello",
}

func (c *greeterClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/greeter.v2.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var greeterSayGoodbyeStreamDesc = &grpc.StreamDesc{
	StreamName: "SayGoodbye",
}

func (c *greeterClient) SayGoodbye(ctx context.Context, in *SayGoodbyeRequest, opts ...grpc.CallOption) (*SayGoodbyeResponse, error) {
	out := new(SayGoodbyeResponse)
	err := c.cc.Invoke(ctx, "/greeter.v2.Greeter/SayGoodbye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterService is the service API for Greeter service.
// Fields should be assigned to their respective handler implementations only before
// RegisterGreeterService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type GreeterService struct {
	// SayHello will register a user in the database, and return a nice message
	// to the caller.
	SayHello func(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	// GayGoodbye will remove the user from the database, and return a nice
	// message to the caller.
	SayGoodbye func(context.Context, *SayGoodbyeRequest) (*SayGoodbyeResponse, error)
}

func (s *GreeterService) sayHello(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/greeter.v2.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}
func (s *GreeterService) sayGoodbye(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayGoodbyeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.SayGoodbye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/greeter.v2.Greeter/SayGoodbye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.SayGoodbye(ctx, req.(*SayGoodbyeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterGreeterService registers a service implementation with a gRPC server.
func RegisterGreeterService(s grpc.ServiceRegistrar, srv *GreeterService) {
	srvCopy := *srv
	if srvCopy.SayHello == nil {
		srvCopy.SayHello = func(context.Context, *SayHelloRequest) (*SayHelloResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
		}
	}
	if srvCopy.SayGoodbye == nil {
		srvCopy.SayGoodbye = func(context.Context, *SayGoodbyeRequest) (*SayGoodbyeResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method SayGoodbye not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "greeter.v2.Greeter",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "SayHello",
				Handler:    srvCopy.sayHello,
			},
			{
				MethodName: "SayGoodbye",
				Handler:    srvCopy.sayGoodbye,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "greeter/v2/greeter_api.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewGreeterService creates a new GreeterService containing the
// implemented methods of the Greeter service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewGreeterService(s interface{}) *GreeterService {
	ns := &GreeterService{}
	if h, ok := s.(interface {
		SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	}); ok {
		ns.SayHello = h.SayHello
	}
	if h, ok := s.(interface {
		SayGoodbye(context.Context, *SayGoodbyeRequest) (*SayGoodbyeResponse, error)
	}); ok {
		ns.SayGoodbye = h.SayGoodbye
	}
	return ns
}

// UnstableGreeterService is the service API for Greeter service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableGreeterService interface {
	// SayHello will register a user in the database, and return a nice message
	// to the caller.
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
	// GayGoodbye will remove the user from the database, and return a nice
	// message to the caller.
	SayGoodbye(context.Context, *SayGoodbyeRequest) (*SayGoodbyeResponse, error)
}
